### PR TITLE
feat(#168): comment-without-dot allows comment to end with `?`, `!`

### LINKED ISSUE #168: `comment-without-dot.xsl` complains about other symbols
How about this comment:

```
# Is it a small file?
[] > small
```

Looks perfect to me, but `comment-without-dot.xsl` complains that it doesn't end with a dot. I suggest allowing other punctuation symbols too, at the end of a comment: `:`, `?`, `!`.

### PR DESCRIPTION
**Pull request by h1alexbel**
In this pull I've updated `comment-without-dot` lint to allow comment to end with other special symbols too: `?`, `!`.

closes #168

### CODE REVIEW

**Comment by h1alexbel** [comment]
@maxonfjvipon please check

**Comment by maxonfjvipon** [comment]
@h1alexbel let's wait for @yegor256 answering to [this](https://github.com/objectionary/lints/issues/168#issuecomment-2561934473)

**Comment by h1alexbel** [comment]
@maxonfjvipon updated. Take a look, please

**Review by maxonfjvipon — APPROVED** [review]

**Comment by h1alexbel** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@h1alexbel thanks!

**Pull request merged**
