### PR TITLE
feat(#112): unit-test-without-live-file lint

### LINKED ISSUE #112: test file must match with a live file
If `foo-test.eo` file exists, there must be `foo.eo` file too. Let's create a lint that will check this and issue a `warning` if this rule is violated.

### PR DESCRIPTION
**Pull request by h1alexbel**
In this pull I've introduced new lint: `unit-test-without-live-file`, that issues `warning` defect in case unit test file does not match with live file, e.g. `foo-test -> bar`.

closes #112
History:
- **feat(#112): unit-test-without-live-file**
- **feat(#112): motive, valid xml**
- **feat(#112): wpa**

### CODE REVIEW

**Comment by h1alexbel** [comment]
@yegor256 take a look, please

**Comment by yegor256** [comment]
@h1alexbel looks very good, but there are merge conflicts. Please, merge master into your branch.

**Comment by h1alexbel** [comment]
@yegor256 resolved merge conflict

**Comment by yegor256** [comment]
@h1alexbel thanks!!

**Pull request merged**
