### PR TITLE
feat(#31): unknown-metas lint

### LINKED ISSUE #31: unknown metas must lead to warnings
There is a pretty short list of metas that we currently understand:

```
package
alias
version
tests
rt
architect
home
unlint
```

If any meta aside from them is used, let's issue a warning.

### PR DESCRIPTION
**Pull request by h1alexbel**
In this pull I've introduced new lint: `unknown-metas`, that issues warnings in case of usage metas which are not predefined.

closes #31

### CODE REVIEW

**Comment by h1alexbel** [comment]
@yegor256 take a look, please

**Comment by yegor256** [comment]
@h1alexbel pay attention, we moved all YAML packs to `eo-packs` directory. Please, move yours too, otherwise it doesn't pick up.

**Comment by yegor256** [comment]
@h1alexbel also, there is `probe` meta - it is also valid

**Comment by h1alexbel** [comment]
@yegor256 updated branch, added `+probe` to the list of supported metas

**Pull request merged**
