### PR TITLE
feat(#60): Defect.version

### LINKED ISSUE #60: attach version of the library to every `Defect`
When error is reported, the version of the linter is not known. Let's add method `version` to the `Defect` interface, making it return the current version of the JAR.

### PR DESCRIPTION
**Pull request by h1alexbel**
In this pull I've added new method to the `Defect` interface: `version()`, that returns version of the JAR from pom.xml file.

closes #60
History:
- **feat(#60): maven-model**
- **feat(#60): passes**
- **feat(#60): clean for pmd**

### CODE REVIEW

**Comment by h1alexbel** [comment]
@yegor256 take a look, please

**Comment by yegor256** [comment]
@h1alexbel this won't work in production, because `pom.xml` doesn't exist in the JAR file. See how we've implemented this functionality in another place recently: https://github.com/objectionary/jeo-maven-plugin/pull/899

**Comment by h1alexbel** [comment]
@yegor256 thanks, I will try it

**Comment by h1alexbel** [comment]
@yegor256 updated pull request. Take a look again, please

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
